"""Refactor models: Plugin, Work, Node, User

Revision ID: 42dce66f6f51
Revises: 99ab30cd4059
Create Date: 2026-01-26 13:12:22.388056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42dce66f6f51'
down_revision: Union[str, None] = '99ab30cd4059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.drop_column('agents_manager', 'create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents_manager', sa.Column('create_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
