"""初始化

Revision ID: 4895c3fe4269
Revises: 
Create Date: 2025-12-23 10:26:00.539191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '4895c3fe4269'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_metadata',
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_current_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_is_remove', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_document_metadata_folder_id'), 'document_metadata', ['folder_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_novel_id'), 'document_metadata', ['novel_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_user_id'), 'document_metadata', ['user_id'], unique=False)
    op.create_table('document_version',
    sa.Column('document_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_parent_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_body_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('document_word_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('document_version_id')
    )
    op.create_index(op.f('ix_document_version_document_id'), 'document_version', ['document_id'], unique=False)
    op.create_table('folder',
    sa.Column('folder_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_index(op.f('ix_folder_novel_id'), 'folder', ['novel_id'], unique=False)
    op.create_table('kd',
    sa.Column('kd_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('kd_id')
    )
    op.create_table('novel',
    sa.Column('novel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('novel_update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('novel_is_remove', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_index(op.f('ix_novel_user_id'), 'novel', ['user_id'], unique=False)
    op.create_table('novel_kd_mapping',
    sa.Column('novel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kd_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('novel_id', 'kd_id')
    )
    op.create_table('tree_sort',
    sa.Column('tree_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('novel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tree_id')
    )
    op.create_index(op.f('ix_tree_sort_node_id'), 'tree_sort', ['node_id'], unique=False)
    op.create_index(op.f('ix_tree_sort_novel_id'), 'tree_sort', ['novel_id'], unique=False)
    op.create_index(op.f('ix_tree_sort_parent_id'), 'tree_sort', ['parent_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tree_sort_parent_id'), table_name='tree_sort')
    op.drop_index(op.f('ix_tree_sort_novel_id'), table_name='tree_sort')
    op.drop_index(op.f('ix_tree_sort_node_id'), table_name='tree_sort')
    op.drop_table('tree_sort')
    op.drop_table('novel_kd_mapping')
    op.drop_index(op.f('ix_novel_user_id'), table_name='novel')
    op.drop_table('novel')
    op.drop_table('kd')
    op.drop_index(op.f('ix_folder_novel_id'), table_name='folder')
    op.drop_table('folder')
    op.drop_index(op.f('ix_document_version_document_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_document_metadata_user_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_novel_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_folder_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    # ### end Alembic commands ###
