"""init_unified_schema_v2

Revision ID: 6feb7036b511
Revises: 
Create Date: 2026-01-28 19:22:46.359545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '6feb7036b511'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents_manager',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('broadcast', sa.Boolean(), nullable=False),
    sa.Column('histories', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_work_id'), 'knowledge_base', ['work_id'], unique=False)
    op.create_table('memory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_work_id'), 'memory', ['work_id'], unique=False)
    op.create_table('plugin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_name'), 'plugin', ['name'], unique=True)
    op.create_table('work',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunk',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_kb_id'), 'knowledge_chunk', ['kb_id'], unique=False)
    op.create_table('node',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_work_id'), 'node', ['work_id'], unique=False)
    op.create_table('work_plugin_mapping',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_plugin_mapping_plugin_id'), 'work_plugin_mapping', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_work_plugin_mapping_work_id'), 'work_plugin_mapping', ['work_id'], unique=False)
    op.create_table('document_version',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_version_node_id'), 'document_version', ['node_id'], unique=False)
    op.create_table('node_relationship',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_relationship_from_node_id'), 'node_relationship', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_node_relationship_to_node_id'), 'node_relationship', ['to_node_id'], unique=False)
    op.create_index(op.f('ix_node_relationship_work_id'), 'node_relationship', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_relationship_work_id'), table_name='node_relationship')
    op.drop_index(op.f('ix_node_relationship_to_node_id'), table_name='node_relationship')
    op.drop_index(op.f('ix_node_relationship_from_node_id'), table_name='node_relationship')
    op.drop_table('node_relationship')
    op.drop_index(op.f('ix_document_version_node_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_work_plugin_mapping_work_id'), table_name='work_plugin_mapping')
    op.drop_index(op.f('ix_work_plugin_mapping_plugin_id'), table_name='work_plugin_mapping')
    op.drop_table('work_plugin_mapping')
    op.drop_index(op.f('ix_node_work_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_knowledge_chunk_kb_id'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_table('work')
    op.drop_index(op.f('ix_plugin_name'), table_name='plugin')
    op.drop_table('plugin')
    op.drop_index(op.f('ix_memory_work_id'), table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_knowledge_base_work_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_table('agents_manager')
    # ### end Alembic commands ###
