"""Refactor_to_unified_architecture_v1.1

Revision ID: 99ab30cd4059
Revises: 4895c3fe4269
Create Date: 2026-01-26 13:04:45.824725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99ab30cd4059'
down_revision: Union[str, None] = '4895c3fe4269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents_manager',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('broadcast', sa.Boolean(), nullable=False),
    sa.Column('histories', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_work_id'), 'knowledge_base', ['work_id'], unique=False)
    op.create_table('memory',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('memory_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_work_id'), 'memory', ['work_id'], unique=False)
    op.create_table('plugin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('from_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_name'), 'plugin', ['name'], unique=True)
    op.create_table('work',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_user_id'), 'work', ['user_id'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_kb_id'), 'knowledge_chunk', ['kb_id'], unique=False)
    op.create_table('node',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_parent_id'), 'node', ['parent_id'], unique=False)
    op.create_index(op.f('ix_node_work_id'), 'node', ['work_id'], unique=False)
    op.create_table('work_plugin_mapping',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_plugin_mapping_plugin_id'), 'work_plugin_mapping', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_work_plugin_mapping_work_id'), 'work_plugin_mapping', ['work_id'], unique=False)
    op.create_table('node_relationship',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('work_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_relationship_from_node_id'), 'node_relationship', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_node_relationship_to_node_id'), 'node_relationship', ['to_node_id'], unique=False)
    op.create_index(op.f('ix_node_relationship_work_id'), 'node_relationship', ['work_id'], unique=False)
    op.drop_index(op.f('ix_tree_sort_node_id'), table_name='tree_sort')
    op.drop_index(op.f('ix_tree_sort_novel_id'), table_name='tree_sort')
    op.drop_index(op.f('ix_tree_sort_parent_id'), table_name='tree_sort')
    op.drop_table('tree_sort')
    op.drop_index(op.f('ix_document_metadata_folder_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_novel_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_user_id'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_folder_novel_id'), table_name='folder')
    op.drop_table('folder')
    op.drop_table('novel_kd_mapping')
    op.drop_index(op.f('ix_novel_user_id'), table_name='novel')
    op.drop_table('novel')
    op.drop_table('kd')
    op.add_column('document_version', sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document_version', sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document_version', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('document_version', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('document_version', sa.Column('create_time', sa.TIMESTAMP(timezone=True), nullable=False))
    op.drop_index(op.f('ix_document_version_document_id'), table_name='document_version')
    op.create_index(op.f('ix_document_version_node_id'), 'document_version', ['node_id'], unique=False)
    op.create_foreign_key(None, 'document_version', 'node', ['node_id'], ['id'])
    op.drop_column('document_version', 'document_word_count')
    op.drop_column('document_version', 'document_version_id')
    op.drop_column('document_version', 'document_id')
    op.drop_column('document_version', 'document_body_text')
    op.drop_column('document_version', 'document_parent_version_id')
    op.drop_column('document_version', 'document_create_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_version', sa.Column('document_create_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('document_version', sa.Column('document_parent_version_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_version', sa.Column('document_body_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_version', sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_version', sa.Column('document_version_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('document_version', sa.Column('document_word_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_version', type_='foreignkey')
    op.drop_index(op.f('ix_document_version_node_id'), table_name='document_version')
    op.create_index(op.f('ix_document_version_document_id'), 'document_version', ['document_id'], unique=False)
    op.drop_column('document_version', 'create_time')
    op.drop_column('document_version', 'word_count')
    op.drop_column('document_version', 'content')
    op.drop_column('document_version', 'node_id')
    op.drop_column('document_version', 'id')
    op.create_table('kd',
    sa.Column('kd_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('kd_id', name=op.f('kd_pkey'))
    )
    op.create_table('novel',
    sa.Column('novel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_create_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('novel_update_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('novel_is_remove', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('novel_id', name=op.f('novel_pkey'))
    )
    op.create_index(op.f('ix_novel_user_id'), 'novel', ['user_id'], unique=False)
    op.create_table('novel_kd_mapping',
    sa.Column('novel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('kd_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('novel_id', 'kd_id', name=op.f('novel_kd_mapping_pkey'))
    )
    op.create_table('folder',
    sa.Column('folder_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('folder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('folder_create_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('folder_id', name=op.f('folder_pkey'))
    )
    op.create_index(op.f('ix_folder_novel_id'), 'folder', ['novel_id'], unique=False)
    op.create_table('document_metadata',
    sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_current_version_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_update_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('document_is_remove', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('document_id', name=op.f('document_metadata_pkey'))
    )
    op.create_index(op.f('ix_document_metadata_user_id'), 'document_metadata', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_novel_id'), 'document_metadata', ['novel_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_folder_id'), 'document_metadata', ['folder_id'], unique=False)
    op.create_table('tree_sort',
    sa.Column('tree_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('novel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('node_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tree_id', name=op.f('tree_sort_pkey'))
    )
    op.create_index(op.f('ix_tree_sort_parent_id'), 'tree_sort', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tree_sort_novel_id'), 'tree_sort', ['novel_id'], unique=False)
    op.create_index(op.f('ix_tree_sort_node_id'), 'tree_sort', ['node_id'], unique=False)
    op.drop_index(op.f('ix_node_relationship_work_id'), table_name='node_relationship')
    op.drop_index(op.f('ix_node_relationship_to_node_id'), table_name='node_relationship')
    op.drop_index(op.f('ix_node_relationship_from_node_id'), table_name='node_relationship')
    op.drop_table('node_relationship')
    op.drop_index(op.f('ix_work_plugin_mapping_work_id'), table_name='work_plugin_mapping')
    op.drop_index(op.f('ix_work_plugin_mapping_plugin_id'), table_name='work_plugin_mapping')
    op.drop_table('work_plugin_mapping')
    op.drop_index(op.f('ix_node_work_id'), table_name='node')
    op.drop_index(op.f('ix_node_parent_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_knowledge_chunk_kb_id'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index(op.f('ix_work_user_id'), table_name='work')
    op.drop_table('work')
    op.drop_index(op.f('ix_plugin_name'), table_name='plugin')
    op.drop_table('plugin')
    op.drop_index(op.f('ix_memory_work_id'), table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_knowledge_base_work_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_table('agents_manager')
    # ### end Alembic commands ###
