"""add_plugin_fields_data_source_render_type

Revision ID: 9f5619e4eeef
Revises: b9cc8a36760e
Create Date: 2026-02-12 01:06:54.617523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f5619e4eeef'
down_revision: Union[str, None] = 'b9cc8a36760e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('checkpoints')
    # op.drop_table('checkpoint_writes')
    
    # Create enum type explicitly
    render_type_enum = sa.Enum('LIST', 'DETAIL', 'DASHBOARD', name='rendertype')
    render_type_enum.create(op.get_bind())
    
    op.add_column('plugin', sa.Column('data_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plugin', sa.Column('render_type', render_type_enum, nullable=False, server_default='LIST'))
    op.add_column('plugin', sa.Column('auth_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plugin', 'auth_config')
    op.drop_column('plugin', 'render_type')
    op.drop_column('plugin', 'data_source_url')
    
    # Drop enum type explicitly
    render_type_enum = sa.Enum('LIST', 'DETAIL', 'DASHBOARD', name='rendertype')
    render_type_enum.drop(op.get_bind())
    
    # op.create_table('checkpoint_writes',
    # sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    # )
    # op.create_table('checkpoints',
    # sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('checkpoint_type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.Column('metadata_type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('metadata_blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    # )
    # ### end Alembic commands ###
