"""update_schema_version_to_str

Revision ID: b9cc8a36760e
Revises: 300e36278979
Create Date: 2026-01-31 18:25:09.015473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9cc8a36760e'
down_revision: Union[str, None] = '300e36278979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('checkpoints')
    # op.drop_table('checkpoint_writes')
    op.alter_column('node', 'now_version',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'now_version',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    # op.create_table('checkpoint_writes',
    # sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    # )
    # op.create_table('checkpoints',
    # sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('checkpoint_type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('checkpoint_blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.Column('metadata_type', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('metadata_blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    # )
    # ### end Alembic commands ###
